org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -Dkotlin.daemon.jvm.options=-Xmx2G
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false
android.compileSdkVersion=36
android.minSdkVersion=21
android.targetSdkVersion=36
org.gradle.java.home=C:\\Program Files\\Java\\jdk-17.0.1